# -*- coding: utf-8 -*-
"""Faststart-remux scene clips (web streaming) + write real durations into manifest."""
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CLIPS = ROOT / "assets" / "clips"
SCENES_DIR = ROOT / "assets" / "scenes"


def probe_dur(p):
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(p)],
        capture_output=True, text=True)
    return round(float(out.stdout.strip()), 2)


for mp4 in sorted(CLIPS.glob("scene-*.mp4")):
    tmp = mp4.with_suffix(".fast.mp4")
    r = subprocess.run(["ffmpeg", "-y", "-i", str(mp4), "-c", "copy",
                        "-movflags", "+faststart", str(tmp)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print(f"FAIL {mp4.name}: {r.stderr[-300:]}")
        continue
    tmp.replace(mp4)
    print(f"faststart: {mp4.name}  ({mp4.stat().st_size/1e6:.1f} MB)")

mf = json.loads((SCENES_DIR / "manifest.json").read_text("utf-8"))
for sc in mf["scenes"]:
    p = CLIPS / f"scene-{sc['id']}.mp4"
    sc["dur"] = probe_dur(p)
(SCENES_DIR / "manifest.json").write_text(json.dumps(mf, indent=2), "utf-8")
js = "// generated by tools/build_assets.py + remux.py -- do not edit\nwindow.NA_MANIFEST = " + json.dumps(mf, indent=2) + ";\n"
(ROOT / "src" / "data.js").write_text(js, "utf-8")
print("manifest durations:", [(s['id'], s['dur']) for s in mf['scenes']])
